const slugify = require('slugify');

// Mirrors the frontend's toSlug() so URLs generated by either side match:
// lowercase, spaces -> hyphens, strip non [a-z0-9-] chars, collapse repeats.
const toSlug = (name) =>
  slugify(name || '', { lower: true, strict: true, trim: true });

module.exports = toSlug;
